#!/bin/bash

while [ ! $1 ]; do
	eval $(xdotool getactivewindow getwindowgeometry --shell)
	WX=$X
	WY=$Y
	eval $(xdotool getmouselocation --shell)
	berryc window_resize_absolute $(echo "$X - $WX" | bc) $(echo "$Y - $WY" | bc)
done

pkill -o -f $0
berryc window_move 0 0
