#!/bin/bash

#get calendar string
_cal=$(cal -m --color=always)

# mark current date
replacement1="s/\x1b\[7m/<span background=\"#50739c\"><b>/"
replacement2="s/\x1b\[27m/<\/b><\/span>/"

res=$(echo -e "$_cal" | sed -e "$replacement1" | sed -e "$replacement2")

# echo $res
notify-send ' calendar' "$res"
