#!/bin/bash

mkdir -p /tmp/screenshot

file="/tmp/screenshot/screenshot.png"

maim -g $(slop) $file

echo "file://$file" | xclip -i -selection clipboard -target "text/uri-list"

notify-send " take screenshot" "screenshot saved to clipboard and file: [$file]"
